{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "6.9",
      "buildId" : "rv5jdblfn5drvnzbd4fz3wx5ge"
    }
  },
  "component" : {
    "group" : "com.github.dhaval2404",
    "module" : "imagepicker",
    "version" : "v2.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "imagepicker-v2.0.aar",
      "url" : "imagepicker-v2.0.aar",
      "size" : 101874,
      "sha512" : "ae3d2c942cc0742c34ba7f10ade918237fd8674c73cc4768d1d5a55c34b73e56b1f5744879c6ed786d4d6653edce585a6f7817a8ccb17e40aef4fd0fa4a8e27e",
      "sha256" : "4723d3198565758952e0b921c5b2b99309faa60ba939ef7715a22b34898c5304",
      "sha1" : "270aa889fa5c56e4b5a346a1a5b7ffa94d8f5b4a",
      "md5" : "121de6defa8e1d9674ed979646c2bc50"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk7",
      "version" : {
        "requires" : "1.4.0"
      }
    }, {
      "group" : "androidx.core",
      "module" : "core-ktx",
      "version" : {
        "requires" : "1.3.2"
      }
    }, {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.2.0"
      }
    }, {
      "group" : "androidx.exifinterface",
      "module" : "exifinterface",
      "version" : {
        "requires" : "1.3.2"
      }
    }, {
      "group" : "androidx.documentfile",
      "module" : "documentfile",
      "version" : {
        "requires" : "1.0.1"
      }
    }, {
      "group" : "com.github.yalantis",
      "module" : "ucrop",
      "version" : {
        "requires" : "2.2.6"
      }
    } ],
    "files" : [ {
      "name" : "imagepicker-v2.0.aar",
      "url" : "imagepicker-v2.0.aar",
      "size" : 101874,
      "sha512" : "ae3d2c942cc0742c34ba7f10ade918237fd8674c73cc4768d1d5a55c34b73e56b1f5744879c6ed786d4d6653edce585a6f7817a8ccb17e40aef4fd0fa4a8e27e",
      "sha256" : "4723d3198565758952e0b921c5b2b99309faa60ba939ef7715a22b34898c5304",
      "sha1" : "270aa889fa5c56e4b5a346a1a5b7ffa94d8f5b4a",
      "md5" : "121de6defa8e1d9674ed979646c2bc50"
    } ]
  } ]
}